"""Add tryon_image_url to outfits

Revision ID: 15ff3c5100fe
Revises: 0e82cca66610
Create Date: 2025-07-08 16:19:18.773655

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '15ff3c5100fe'
down_revision = '0e82cca66610'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outfits', sa.Column('tryon_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outfits', 'tryon_image_url')
    # ### end Alembic commands ### 