"""moderator role

Revision ID: 2ddf7db02d9a
Revises: 15ff3c5100fe
Create Date: 2025-07-09 05:40:53.936855

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2ddf7db02d9a'
down_revision = '15ff3c5100fe'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_items_owner_id'), 'items', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'items', 'users', ['owner_id'], ['id'])
    op.add_column('users', sa.Column('is_moderator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_moderator')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_index(op.f('ix_items_owner_id'), table_name='items')
    op.drop_column('items', 'owner_id')
    # ### end Alembic commands ### 