"""Remove collection field from items table

Revision ID: 450f86df46ab
Revises: 7a2b4f8c9d1e
Create Date: 2025-07-02 18:15:17.158763

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '450f86df46ab'
down_revision = '7a2b4f8c9d1e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 