"""remove collection from outfits

Revision ID: 7a2b4f8c9d1e
Revises: 57fe8863cb14
Create Date: 2024-01-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2b4f8c9d1e'
down_revision = '57fe8863cb14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outfits_collection', table_name='outfits')
    op.drop_column('outfits', 'collection')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outfits', sa.Column('collection', sa.VARCHAR(length=100), nullable=True))
    op.create_index('ix_outfits_collection', 'outfits', ['collection'], unique=False)
    # ### end Alembic commands ### 