"""add_ai_generated_image_to_outfits

Revision ID: d8a3d101251f
Revises: 450f86df46ab
Create Date: 2025-07-03 10:22:30.499155

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd8a3d101251f'
down_revision = '450f86df46ab'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outfits', sa.Column('ai_generated_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outfits', 'ai_generated_image')
    # ### end Alembic commands ### 