"""add created_at to user and is_public to outfit

Revision ID: e42b1b587057
Revises: c047ce166c35
Create Date: 2025-07-12 17:47:24.778149

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e42b1b587057'
down_revision = 'c047ce166c35'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outfits', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('outfits', 'is_public')
    # ### end Alembic commands ### 