"""remove_ai_generated_image_from_outfits

Revision ID: remove_ai_generated_image
Revises: d8a3d101251f
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'remove_ai_generated_image'
down_revision = 'd8a3d101251f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outfits', 'ai_generated_image')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outfits', sa.Column('ai_generated_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ### 